server:
  port: 8080

spring:
  application:
    name: take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  cache:
    redis:
      time-to-live: 600000
  mail:
    host: smtp.qq.com
    port: 465
    username: 3120363579@qq.com
    password: kzmjtybfxnuodggg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, classpath:/publiwc/, file:/usr/share/images/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

images:
  path: /usr/share/images/  # 容器内部挂载路径